import type { Metadata } from "next";
import Navigation from ".././componets/NavBar";
import { Inter } from "next/font/google";
import styles from './styles.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <section>
        <Navigation />
        {children}
    </section>
  );
}

